version: "3.4"
services:
  postgres:
    hostname: postgres
    image: postgres:14
    restart: always
    volumes:
      - ./postgres/create_db.sh:/docker-entrypoint-initdb.d/20-create_db.sh
      # To persist your PostgreSQL databases outside of the Docker image,
      # to prevent data loss, modify the following ./path_to path:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Qwe233233
      POSTGRES_USER: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

